services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper

  nimbus:
    image: storm:2.8
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 6627:6627

  supervisor:
    image: storm:2.8
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper

  ui:
    image: storm:2.8
    container_name: ui
    command: storm ui
    depends_on:
      - nimbus
    links:
      - nimbus
    ports:
      - 8080:8080

  storm-submit-topology:
    image: storm:2.8
    container_name: storm-submit-topology
    command: /storm/submit-topology.sh
    depends_on:
      - nimbus
    links:
      - nimbus
    volumes:
      - ./storm:/storm
    restart: none

  storm-exporter:
    build: .
    container_name: storm-exporter
    environment:
      - STORM_UI_HOST=ui:8080
      - REFRESH_RATE=10
    depends_on:
      - ui
    links:
      - ui
    ports:
      - 9800:9800

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  setup-grafana:
    image: alpine:3
    container_name: setup-grafana
    entrypoint: /grafana/setup-grafana.sh
    depends_on:
      - grafana
    links:
      - grafana
      - prometheus
    volumes:
      - ./grafana/:/grafana/
    restart: none

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - storm-exporter
    depends_on:
      - storm-exporter
