# Global configuration
global:
  scrape_interval: 15s  # How often to scrape targets (default: 1m)
  evaluation_interval: 15s  # How often to evaluate rules (default: 1m)
  scrape_timeout: 10s  # Maximum time to wait before failing a scrape

# Scrape configurations
scrape_configs:
  # Storm Exporter Metrics
  - job_name: 'storm-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['storm-exporter:9800']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
