name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  CI:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG_NAME#v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}

      - name: Verify Helm Chart
        run: |
          helm lint ./chart

      - name: Package Helm Chart
        run: |
          helm package ./chart --version ${{ env.VERSION }}

      - name: Log in to Helm OCI Registry
        run: |
          helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Push Helm Chart to GHCR
        run: |
          helm push ./prometheus-storm-exporter-${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
